/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 tag.glb --draco 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/tag.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.card.geometry} material={materials.base} />
      <mesh geometry={nodes.clip.geometry} material={materials.metal} />
      <mesh geometry={nodes.clamp.geometry} material={materials.metal} />
    </group>
  )
}

useGLTF.preload('/tag.glb')
